/**
 *
 *
 * =========== Template data ====================
 *
 *
 */
const category = ["TV", "FAN", "STB", "TV_BOX", "LIGHT", "OTHER"];
const brand = [
  "SONY",
  "PANASONIC",
  "SAMSUNG",
  "MITSUBISHI",
  "LG",
  "SHARP",
  "MI",
  "SKYWORTH",
  "TCL",
  "OTHER",
];
const tv_button = {
  0: "0",
  1: "1",
  2: "2",
  3: "3",
  4: "4",
  5: "5",
  6: "6",
  7: "7",
  8: "8",
  9: "9",
  POWER: "Power",
  FAST_BACKWARD: "Fast Backward",
  PLAY: "Play",
  FAST_FORWARD: "Fast Forward",
  PREVIOUS: "Previous",
  PAUSE: "Pause",
  NEXT: "Next",
  STOP: "Stop",
  BACK: "Back",
  HOME: "Home",
  MENU: "Menu",
  UP: "Up",
  DOWN: "Down",
  LEFT: "Left",
  RIGHT: "Right",
  ENTER: "Enter",
  VOLUME_UP: "Volume Up",
  VOLUME_DOWN: "Volume Down",
  MUTE: "Mute",
  CHANNEL_UP: "Channel Up",
  CHANNEL_DOWN: "Channel Down",
  NETFLIX: "Netflix",
  YOUTUBE: "Youtube",
  EXIT: "Exit",
  FAV: "Fav",
  GREEN: "Green",
  BLUE: "Blue",
  OPTION: "Option",
  TV: "Tv",
  HDMI: "Hdmi",
  RED: "Red",
  SUB: "Sub",
  YELLOW: "Yellow",
  HDMI1: "Hdmi1",
  GUIDE: "Guide",
  INFO: "Info",
  SCREEN: "Screen",
  USB: "Usb",
  HDMI2: "Hdmi2",
  HDMI3: "Hdmi3",
  VGA: "Vga",
  PICTURE_MODE: "Picture Mode",
  AUDIO_MODE: "Audio Mode",
  "3D": "3D",
  PIP: "Pip",
  SEARCH: "Search",
  AV: "Av",
  "PRE-CH": "Pre-Ch",
  RECORD: "Record",
  ZOOM: "Zoom",
  SAP: "Sap",
  NORMAL: "Normal",
  PROPORTION: "Proportion",
  VIDEO_SYSTEM: "Video System",
  FREEZE: "Freeze",
  LOOK_OVER: "Look Over",
  "PIP+": "Pip+",
  "PIP-": "Pip-",
  HDTV: "Hdtv",
  NETWORK: "Network",
  TOOLS: "Tools",
  DETAIL: "Detail",
  SETTING: "Setting",
  LIST: "List",
  RESERVATION_LIST: "Reservation List",
  MEDIA: "Media",
  LIVE_BROADCAST: "Live Broadcast",
  SLEEP: "Sleep",
  DISPLAY: "Display",
  SOUND_MODE: "Sound Mode",
  LAST: "Last",
  REWIND: "Rewind",
  HELP: "Help",
  INPUT: "Input",
  OTHER: "",
};

const fan_button = {
  2: "2",
  POWER: "Power",
  1: "1",
  SPIN: "Spin",
  3: "3",
  SPEED: "Speed",
  5: "5",
  SPEED_UP: "Speed_up",
  4: "4",
  SPEED_DOWN: "Speed_down",
  TIMER: "TIMER",
  MODE: "Mode",
};

const set_top_box_button = {
  0: "0",
  1: "1",
  2: "2",
  3: "3",
  4: "4",
  5: "5",
  6: "6",
  7: "7",
  8: "8",
  9: "9",
  POWER: "Power",
  BACK: "Back",
  HOME: "Home",
  MENU: "Menu",
  UP: "Up",
  DOWN: "Down",
  LEFT: "Left",
  RIGHT: "Right",
  ENTER: "Enter",
  VOLUME_UP: "Volume Up",
  VOLUME_DOWN: "Volume Down",
  MUTE: "Mute",
  CHANNEL_UP: "Channel Up",
  CHANNEL_DOWN: "Channel Down",
};
